### ISSUE TITLE
Convert hardcoded account settings menu to dynamic menu

### ISSUE THREAD

**Issue by Omranic** [rinvex/cortex-fort#47]
#40 related

**Comment by noxify** [comment]
What about the "tab" links for settings and attributes?

Currently, we have the problem in the app, that the hash will not be added to the current url.
Based on this, the existing JS code to activate the defined tab will not work.

I have the the following ideas:
1. create a new route with controller actions to have a new page ( a bit overkill? )
2. move the `@attributes($currentUser)` inside the first tab 
3. update the JS inside the `cortex` repo to enable the "hashing" inside the url (https://stackoverflow.com/a/12138756)

**Comment by Omranic** [comment]
Supposedly, we already have the third option, but not sure why it's not working! I guess some conflict when mixing tabs & urls with turbolinks maybe?! Anyway I'll go with the first option as the settings page already bloated! For now I removed the attributes link until we implement the controller/view for it..

**Comment by noxify** [comment]
Ok - but option 1 is a new task/user story?

**Comment by Omranic** [comment]
Yes, but I'd recommend to wait for a while as this package is currently undergoing fundamental refactoring! 😅  Simplifying email verification, TwoFactor authentication, dropping the custom SessionGuard, and utilizing Laravel Multi-Auth features..

**Comment by noxify** [comment]
Waiting for what?

- [ ] Updating the user menu
- [ ] Moving the attributes logic

**Comment by Omranic** [comment]
Done in d28e4bc44b40103fbb44af1a2c17d8d939e0718a 👌
